### ISSUE TITLE
Create AWS kubernetes OU containing k8s-infra-aws-root-account@kubernetes.io AdminAccount

### ISSUE THREAD

**Issue by hh** [cncf/credits#1]
This repo will contain the terraform code at the CNCF Level to create OUs for CNCF Projects. 

Kubernetes is the first project to request AWS funds, so this is the first time we are spinning up this repo.

/assign @BobyMCbobs

**Comment by hh** [comment]
@BobyMCbobs will create two PRs, one for Account within an new org, and another for a new account within an OU. Will get feedback on the approaches, merge and run this week.

**Comment by BobyMCbobs** [comment]
PRs:
- https://github.com/cncf/credits/pull/2
- https://github.com/cncf/credits/pull/3

**Comment by sftim** [comment]
A nit I've mentioned elsewhere, I wouldn't use the term “root” for any AWS account
- if it's the account that manages the organization, the current term is “management account”
- if it's any other AWS account, using “root” in the name / email address might confuse people into thinking that they are dealing with the management account for the organization.

**Comment by BobyMCbobs** [comment]
> A nit I've mentioned elsewhere, I wouldn't use the term “root” for any AWS account
> 
> * if it's the account that manages the organization, the current term is “management account”
> * if it's any other AWS account, using “root” in the name / email address might confuse people into thinking that they are dealing with the management account for the organization.

@sftim, the term root is being used in the PRs, are you referring to one or both of these?
- 1. AWS org(-unit) structure: https://github.com/BobyMCbobs/cncf-credits/blob/1eb0f1ebe78d4f88b5f915b6d8012b437d21c42a/infra/kubernetes/main.tf#L74
- 2. account email: https://github.com/BobyMCbobs/cncf-credits/blob/1eb0f1ebe78d4f88b5f915b6d8012b437d21c42a/infra/kubernetes/main.tf#L92

**Comment by sftim** [comment]
In my view both those places are wrong or misleading.

**Comment by hh** [comment]
Fair, I think the terminology comes from the folder structure of orgs vs ou.

![image](https://user-images.githubusercontent.com/31331/152422679-d570c839-c254-46d8-b834-fdec09085ede.png)

k8s-infra-aws-root-account@kubernetes.io is currently tied to a google group and mailing list.

@arnaud and @dims would you like the CNCF to use a different email / login

**Comment by BobyMCbobs** [comment]
It appears that the account email has been defined in https://github.com/kubernetes/k8s.io/blob/48fa057568e0beea0ea06844eb1eb6b79a24d05e/groups/sig-k8s-infra/groups.yaml#L265 and here https://github.com/kubernetes/k8s.io/blob/48fa057568e0beea0ea06844eb1eb6b79a24d05e/groups/restrictions.yaml#L192

I found that AWS is using the terminology to describe the top level account, which is where I got the capitalized version to reference
![Screenshot from 2022-02-03 09-19-25](https://user-images.githubusercontent.com/8588826/152413636-d3dc0f95-a63e-4903-8a88-9de0d8dc5056.png)

**Comment by ameukam** [comment]
> Fair, I think the terminology comes from the folder structure of orgs vs ou.
> 
> [k8s-infra-aws-root-account@kubernetes.io](mailto:k8s-infra-aws-root-account@kubernetes.io) is currently tied to a google group and mailing list.
> 
> @arnaud and @dims would you like the CNCF to use a different email / login

@hh  Not for the moment. I don't think it's blocking for account creation. I agree it can be misleading but not for us and the account is not supposed to live forever. Once the experiments we plan to build are done we should delete this account (a TODO can added in the terraform) . The e-mail was created with the assumption, we could do https://github.com/cncf/credits/pull/3.

**Comment by jeefy** [comment]
Thanks @ameukam!
