### ISSUE TITLE
Cloud Credits Request: SPIRE

### ISSUE THREAD

**Issue by jeefy** [cncf/credits#6]
**Copying over from Service Desk** -- Original Submitter: @rturner3

I am a maintainer on the SPIRE project. SPIRE has several integrations with public cloud infrastructure and platform services in AWS, Azure, and GCP to enable users to run SPIRE in these environments.

Examples:
https://github.com/spiffe/spire/blob/main/doc/plugin_server_notifier_gcs_bundle.md
https://github.com/spiffe/spire/blob/main/doc/plugin_server_noderesolver_azure_msi.md
https://github.com/spiffe/spire/blob/main/doc/plugin_server_nodeattestor_aws_iid.md
https://github.com/spiffe/spire/blob/main/doc/plugin_server_keymanager_aws_kms.md
https://github.com/spiffe/spire/blob/main/doc/plugin_agent_svidstore_gcp_secretmanager.md
https://github.com/spiffe/spire/blob/main/doc/plugin_agent_svidstore_aws_secretsmanager.md

It is a challenge for us to support these integrations today because in order to test them and verify they do not have regressions over time, we as maintainers either rely on the community that uses these integrations or pay for public cloud account resources out of our own pockets. Neither of these options are ideal for our community or the maintainer group.

---
@jeefy note: 
AWS: $100/mo
GCP: $100/mo
---

Ryan Turner 
February 18, 2022, 1:26 PM

Hi Ihor,

AWS: A budget of $100/mo should work for us.

GCP: The SPIRE project maintainers are unsure what our current budget is. Would you be able to let us know? Once we know the current budget, we could estimate if our usage will require a different budget.

Regarding account access:

The SPIRE project maintainers use a Google Group [spire-maintainers@spiffe.io](mailto:spire-maintainers@spiffe.io) for access control. Would it be possible to associate public cloud access with that group email? For GCP, it seems possible based on the IAM docs I read, but I’m less familiar with how it might work in AWS. That would be ideal for us since it would give us some ability to add/remove access based on additions/removals of project maintainers over time. For example, David Langhorst has not been associated with SPIRE for several years and should no longer need access to our GCP account.

If setting up account access via the Google Group is not possible, could you at the very least add me as an authorized user?

Regarding GCP access, from what I’ve been told by Evan Gilman, there is also a G Suite account for the SPIFFE project. We would want to keep the access to this G Suite account separate from the GCP account since different people maintain those. I don’t know so much about how those accounts are administrated, but it would be great if you could clarify whether or not their permissions are interrelated.

Thanks again for your help so far.
---

Ryan Turner 
March 17, 2022, 12:16 PM

Hi, just wanted to check in to see when the AWS and GCP project credits might be available to us. We are working on some changes to SPIRE that require public cloud testing and are trying to get a sense of when we might be able to finish those for our release planning. 

Thanks for you help so far!

**Comment by hh** [comment]
/assign @BobyMCbobs 
Caleb and I can help with creating the AWS Org + IAM roles with correct permissions.
This sounds like it may be a partial migration as well.

**Comment by hh** [comment]
@BobyMCbobs possibly drop by the SPIRE booth, if there is one, at KubeCon and say hi!

**Comment by rturner3** [comment]
Is there any update here? Just wondering when we can expect to have access to an AWS environment. We are waiting on merging some AWS-specific changes in SPIRE until we can verify them in AWS.

**Comment by rturner3** [comment]
Hey checking in again since it's been a while since we heard back. Is there any rough ETA we can expect to receive these credits? Thank you!

**Comment by BobyMCbobs** [comment]
Hi folks,

I've made a PR for adding the SPIRE AWS account with base configurations.

https://github.com/cncf/credits/pull/16

I need a few pieces of information the PR can be made ready

- specifically what AWS services need to be accessed?
  - kms?
  - iid?
  - ec2?
- what are the emails of who will access the account? (for IAM users)
- requested budget is $100/mo USD?

depends on: #15 

cc @azdagron @rturner3

**Comment by rturner3** [comment]
We need access to the following AWS services:
- EC2
- KMS
- Secrets Manager
- Certificate Manager Private CA

The emails that need access are:
- azdagron@gmail.com
- ryan.turner253@icloud.com
- amartinezfayo@gmail.com
- evan2645@gmail.com
- marcosyacob@gmail.com

The budget we are requesting is actually $500/mo. We originally overlooked the cost of Certificate Manager Private CA, which @azdagron pointed out is $400/mo on its own.

**Comment by BobyMCbobs** [comment]
@rturner3, I want to make sure that the permissions are set right for your role testing; do the following permissions fit your use case?
https://github.com/cncf/credits/pull/16/commits/13656264272015b9874eec27b66b76a06bda4a2c#diff-f64d152ebff51966198767624dd949802bb235a1c6e5698b45a335e91cda5623R78-R124

I've updated the budget to fit the request as well.

**Comment by rturner3** [comment]
> @rturner3, I want to make sure that the permissions are set right for your role testing; do the following permissions fit your use case? [1365626#diff-f64d152ebff51966198767624dd949802bb235a1c6e5698b45a335e91cda5623R78-R124](https://github.com/cncf/credits/commit/13656264272015b9874eec27b66b76a06bda4a2c#diff-f64d152ebff51966198767624dd949802bb235a1c6e5698b45a335e91cda5623R78-R124)
> 
> I've updated the budget to fit the request as well.

Based on the [AWS IAM documentation](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_use_switch-role-ec2.html#roles-usingrole-ec2instance-permissions) for assuming roles in applications running on EC2, I think there are a few more permissions we need in order to test IAM role assumption:

- `iam:AddRoleToInstanceProfile`
- `iam:CreateInstanceProfile`
- `iam:DeleteInstanceProfile`
- `iam:GetInstanceProfile`
- `iam:ListInstanceProfileTags`
- `iam:ListInstanceProfiles`
- `iam:ListInstanceProfilesForRole`
- `iam:RemoveRoleFromInstanceProfile`
- `iam:TagInstanceProfile`
- `iam:UntagInstanceProfile`

**Comment by BobyMCbobs** [comment]
> > @rturner3, I want to make sure that the permissions are set right for your role testing; do the following permissions fit your use case? [1365626#diff-f64d152ebff51966198767624dd949802bb235a1c6e5698b45a335e91cda5623R78-R124](https://github.com/cncf/credits/commit/13656264272015b9874eec27b66b76a06bda4a2c#diff-f64d152ebff51966198767624dd949802bb235a1c6e5698b45a335e91cda5623R78-R124)
> > I've updated the budget to fit the request as well.
> 
> Based on the [AWS IAM documentation](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_use_switch-role-ec2.html#roles-usingrole-ec2instance-permissions) for assuming roles in applications running on EC2, I think there are a few more permissions we need in order to test IAM role assumption:
> 
> * `iam:AddRoleToInstanceProfile`
> * `iam:CreateInstanceProfile`
> * `iam:DeleteInstanceProfile`
> * `iam:GetInstanceProfile`
> * `iam:ListInstanceProfileTags`
> * `iam:ListInstanceProfiles`
> * `iam:ListInstanceProfilesForRole`
> * `iam:RemoveRoleFromInstanceProfile`
> * `iam:TagInstanceProfile`
> * `iam:UntagInstanceProfile`

@rturner3, I've updated the permissions here.
https://github.com/cncf/credits/pull/16/commits/bafa09f7523b48d4242e1677adb739bd43a9c352

Still awaiting a final review and approval. Will keep you updated

**Comment by rturner3** [comment]
The permissions look good to me now, thanks!

**Comment by BobyMCbobs** [comment]
Update!

# Provisioning and access

The account has been provisioned and made read for use.
The last thing I am to figure out is providing the folks listed (via emails here https://github.com/cncf/credits/issues/6#issuecomment-1196009456) with their credentials.

---

cc @rturner3 @jeefy @hh @riaankl

**Comment by azdagron** [comment]
Did this actually get completed?

**Comment by azdagron** [comment]
@BobyMCbobs, can you confirm?

**Comment by rturner3** [comment]
@BobyMCbobs Were you able to get credentials set up for the requested users? It looks like this got auto-closed by a bot, but we haven't gotten access to an AWS environment yet.

**Comment by BobyMCbobs** [comment]
@azdagron, @rturner3,
apologies for this getting away.

Currently unable to find the following folks on ~~CNCF~~ SPIRE Slack
- [x] amartinezfayo@gmail.com
- [x] azdagron@gmail.com
- [x] evan2645@gmail.com
