### ISSUE TITLE
Cloud Credits Request: Cilium

### ISSUE THREAD

**Issue by jeefy** [cncf/credits#9]
Copying over from Service Desk -- Original Submitter: @lizrice

We're interested in applying for cloud credits to run Cilium tests (which we currently run in AWS, GCP and Azure) 

---

Chris Aniszczyk 
March 29, 2022, 4:42 AM

do you need it for a specific cloud or can you just use [GitHub - cncf/cluster: 🖥🖥🖥🖥CNCF Community Cluster](https://github.com/cncf/cluster)  paired with github actions

**Comment by lizrice** [comment]
We have quite a few CI jobs running on Equinix metal already, right @nbusseneau? Would there be work to do to move our existing jobs to the CNCF community cluster, or is it just a case of applying credit to an account (which obviously would be easier!)

**Comment by hh** [comment]
Checking in with Ed at Packet if we can just apply or relocate it under the primary CNCF account.

**Comment by hh** [comment]
@nbusseneau which Equinox Metal Project are your existing CI jobs running under? I don't see them under the main account. Possibly Ed can just move that account under our umbrella.
